type Address {
  id: Int!
  normAddress: String!
  zip5: String!
  streetNumber: String
  streetName: String
  unit: String
  city: String
  state: String
  county: String
  canonical: String!
  fullAddress: String!
  normalizedAddress: String!
  zip: String
  personAssociations(source: Source = null, role: AddressAssociationRole = null, limit: Int = null, offset: Int = null): PersonAddressAssociationConnection!
  propertyAssociations(source: Source = null, role: PropertyAddressRole = null, limit: Int = null, offset: Int = null): PropertyAddressAssociationConnection!
  sourceRecords(source: Source = null, role: AddressAssociationRole = null, limit: Int = null, offset: Int = null): SourceRecordConnection!
  residents(limit: Int = null, offset: Int = null): PersonConnection!
  people(relationTypes: [String!] = null, limit: Int = null, offset: Int = null): PersonConnection!
  baseRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  utilityRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  taxProperties(limit: Int = null, offset: Int = null): SourceRecordConnection!
  ownerMailingOf(limit: Int = null, offset: Int = null): SourceRecordConnection!
  traceRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  autoRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  loanRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  driveRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  voterRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  criminalRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
}

enum AddressAssociationRole {
  RESIDENCE
  SERVICE_ADDRESS
  LICENSE_ADDRESS
  REGISTRATION_ADDRESS
  MAILING_ADDRESS
  RECORD_ADDRESS
  TRACE_ADDRESS
}

type AddressConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [Address!]!
}

type AddressSearchConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [AddressSearchResult!]!
}

type AddressSearchResult {
  matchScore: Float!
  matchedFields: [String!]!
  address: Address!
  relationCount: Int!
}

input AddressWhereInput {
  normAddress: StringFilterInput = null
  zip5: StringFilterInput = null
  streetNumber: StringFilterInput = null
  streetName: StringFilterInput = null
  unit: StringFilterInput = null
  city: StringFilterInput = null
  state: StringFilterInput = null
  county: StringFilterInput = null
}

type AutoRecord {
  rowid: Int!
  norm: AutoRecordNorm!
  id: String
  autoId: String
  vin: String
  zip: String
  city: String
  make: String
  model: String
  year: String
  phone: String
  address: String
  housenumber: String
  firstname: String
  lastname: String
  person: Person
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type AutoRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [AutoRecord!]!
}

type AutoRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
  phone: String
}

input AutoRecordWhereInput {
  id: StringFilterInput = null
  autoId: StringFilterInput = null
  vin: StringFilterInput = null
  zip: StringFilterInput = null
  city: StringFilterInput = null
  make: StringFilterInput = null
  model: StringFilterInput = null
  year: StringFilterInput = null
  phone: StringFilterInput = null
  address: StringFilterInput = null
  housenumber: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type BaseRecord {
  rowid: Int!
  norm: BaseRecordNorm!
  firstname: String
  middlename: String
  lastname: String
  housenumber: String
  primaryaddress: String
  state: String
  zip: String
  city: String
  phone: String
  estimatedincomecode: String
  homeownerprobabilitymodel: String
  lengthofresidence: String
  presenceofchildren: String
  persongender: String
  persondateofbirthyear: String
  persondateofbirthmonth: String
  persondateofbirthday: String
  personmaritalstatus: String
  personeducation: String
  businessowner: String
  creditrating: String
  networth: String
  homepurchaseprice: String
  homepurchasedateyear: String
  homeyearbuilt: String
  estimatedcurrenthomevaluecode: String
  mortgageamountinthousands: String
  mortgagelendername: String
  deeddateofrefinanceyear: String
  refinanceamountinthousands: String
  refinancelendername: String
  dob: String
  id: String
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type BaseRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [BaseRecord!]!
}

type BaseRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
  primaryaddress: String
  phone: String
}

input BaseRecordWhereInput {
  firstname: StringFilterInput = null
  middlename: StringFilterInput = null
  lastname: StringFilterInput = null
  housenumber: StringFilterInput = null
  primaryaddress: StringFilterInput = null
  state: StringFilterInput = null
  zip: StringFilterInput = null
  city: StringFilterInput = null
  phone: StringFilterInput = null
  estimatedincomecode: StringFilterInput = null
  homeownerprobabilitymodel: StringFilterInput = null
  lengthofresidence: StringFilterInput = null
  presenceofchildren: StringFilterInput = null
  persongender: StringFilterInput = null
  persondateofbirthyear: StringFilterInput = null
  persondateofbirthmonth: StringFilterInput = null
  persondateofbirthday: StringFilterInput = null
  personmaritalstatus: StringFilterInput = null
  personeducation: StringFilterInput = null
  businessowner: StringFilterInput = null
  creditrating: StringFilterInput = null
  networth: StringFilterInput = null
  homepurchaseprice: StringFilterInput = null
  homepurchasedateyear: StringFilterInput = null
  homeyearbuilt: StringFilterInput = null
  estimatedcurrenthomevaluecode: StringFilterInput = null
  mortgageamountinthousands: StringFilterInput = null
  mortgagelendername: StringFilterInput = null
  deeddateofrefinanceyear: StringFilterInput = null
  refinanceamountinthousands: StringFilterInput = null
  refinancelendername: StringFilterInput = null
  dob: StringFilterInput = null
  id: StringFilterInput = null
  nameKey: StringFilterInput = null
  address: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type Contact {
  id: Int!
  contactType: String!
  value: String!
}

type ContactConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [Contact!]!
}

type CriminalRecord {
  rowid: Int!
  norm: CriminalRecordNorm!
  id: String
  criminalId: String
  category: String
  offensedesc1: String
  counts: String
  sourcename: String
  county: String
  arrestdate: String
  admitteddate: String
  releasedate: String
  offensedate: String
  chargesfileddate: String
  sentenceyyymmddd: String
  firstname: String
  middlename: String
  lastname: String
  age: String
  dob: String
  dobDay: String
  dobMonth: String
  dobYear: String
  address: String
  city: String
  state: String
  zip: String
  height: String
  weight: String
  eye: String
  hair: String
  scarsmarks: String
  person: Person
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type CriminalRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [CriminalRecord!]!
}

type CriminalRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
}

input CriminalRecordWhereInput {
  id: StringFilterInput = null
  criminalId: StringFilterInput = null
  category: StringFilterInput = null
  offensedesc1: StringFilterInput = null
  counts: StringFilterInput = null
  sourcename: StringFilterInput = null
  county: StringFilterInput = null
  arrestdate: StringFilterInput = null
  admitteddate: StringFilterInput = null
  releasedate: StringFilterInput = null
  offensedate: StringFilterInput = null
  chargesfileddate: StringFilterInput = null
  sentenceyyymmddd: StringFilterInput = null
  firstname: StringFilterInput = null
  middlename: StringFilterInput = null
  lastname: StringFilterInput = null
  age: StringFilterInput = null
  dob: StringFilterInput = null
  dobDay: StringFilterInput = null
  dobMonth: StringFilterInput = null
  dobYear: StringFilterInput = null
  address: StringFilterInput = null
  city: StringFilterInput = null
  state: StringFilterInput = null
  zip: StringFilterInput = null
  height: StringFilterInput = null
  weight: StringFilterInput = null
  eye: StringFilterInput = null
  hair: StringFilterInput = null
  scarsmarks: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type DriveRecord {
  rowid: Int!
  norm: DriveRecordNorm!
  id: String
  driveId: String
  dlNum: String
  dlState: String
  zip: String
  address: String
  firstname: String
  lastname: String
  person: Person
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type DriveRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [DriveRecord!]!
}

type DriveRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
}

input DriveRecordWhereInput {
  id: StringFilterInput = null
  driveId: StringFilterInput = null
  dlNum: StringFilterInput = null
  dlState: StringFilterInput = null
  zip: StringFilterInput = null
  address: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type EntityEdge {
  id: Int!
  fromType: String!
  fromId: String!
  toType: String!
  toId: String!
  relationType: String!
  source: String!
  sourceRowid: Int!
  confidence: Float!
  evidenceRole: String!
}

type EntityEdgeConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [EntityEdge!]!
}

"""
The `JSON` scalar type represents JSON values as specified by [ECMA-404](https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf).
"""
scalar JSON @specifiedBy(url: "https://ecma-international.org/wp-content/uploads/ECMA-404_2nd_edition_december_2017.pdf")

type LinkedInRecord {
  rowid: Int!
  norm: LinkedInRecordNorm!
  id: String
  linkedinId: String
  firstname: String
  lastname: String
  linkedinurl: String
  pictureurl: String
  locationLinkedintext: String
  summary: String
  premium: String
  openprofile: String
  positionIndex: String
  positionTitle: String
  positionCompanyname: String
  positionCompanyid: String
  positionCompanylinkedinurl: String
  positionCurrent: String
  positionStartedonYear: String
  positionStartedonMonth: String
  positionTenureatcompanyNumyears: String
  positionTenureatcompanyNummonths: String
  positionTenureatpositionNumyears: String
  positionTenureatpositionNummonths: String
  positionDescription: String
  person: Person
}

type LinkedInRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [LinkedInRecord!]!
}

type LinkedInRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
}

input LinkedInRecordWhereInput {
  id: StringFilterInput = null
  linkedinId: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  linkedinurl: StringFilterInput = null
  pictureurl: StringFilterInput = null
  locationLinkedintext: StringFilterInput = null
  summary: StringFilterInput = null
  premium: StringFilterInput = null
  openprofile: StringFilterInput = null
  positionIndex: StringFilterInput = null
  positionTitle: StringFilterInput = null
  positionCompanyname: StringFilterInput = null
  positionCompanyid: StringFilterInput = null
  positionCompanylinkedinurl: StringFilterInput = null
  positionCurrent: StringFilterInput = null
  positionStartedonYear: StringFilterInput = null
  positionStartedonMonth: StringFilterInput = null
  positionTenureatcompanyNumyears: StringFilterInput = null
  positionTenureatcompanyNummonths: StringFilterInput = null
  positionTenureatpositionNumyears: StringFilterInput = null
  positionTenureatpositionNummonths: StringFilterInput = null
  positionDescription: StringFilterInput = null
  nameKey: StringFilterInput = null
  address: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type LoanRecord {
  rowid: Int!
  norm: LoanRecordNorm!
  id: String
  loanId: String
  loanAmount: String
  monthlyIncome: String
  monthPay: String
  ownRent: String
  employer: String
  occupation: String
  address: String
  zip: String
  firstname: String
  lastname: String
  person: Person
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type LoanRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [LoanRecord!]!
}

type LoanRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
}

input LoanRecordWhereInput {
  id: StringFilterInput = null
  loanId: StringFilterInput = null
  loanAmount: StringFilterInput = null
  monthlyIncome: StringFilterInput = null
  monthPay: StringFilterInput = null
  ownRent: StringFilterInput = null
  employer: StringFilterInput = null
  occupation: StringFilterInput = null
  address: StringFilterInput = null
  zip: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type NameObservation {
  id: Int!
  personId: String
  fullName: String
  firstname: String
  middlename: String
  lastname: String
  normNameKey: String
  source: String!
  sourceRowid: Int!
  confidence: Float!
  person: Person
}

type NameObservationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [NameObservation!]!
}

input OrderByInput {
  field: String!
  direction: OrderDirection! = ASC
}

enum OrderDirection {
  ASC
  DESC
}

type Organization {
  id: Int!
  name: String!
  organizationType: String!
  personAssociations(role: OrganizationPersonRole = null, limit: Int = null, offset: Int = null): PersonOrganizationAssociationConnection!
  propertyAssociations(role: PropertyOrganizationRole = null, limit: Int = null, offset: Int = null): PropertyOrganizationAssociationConnection!
}

enum OrganizationPersonRole {
  EMPLOYER
  AFFILIATION
}

type PageInfo {
  totalCount: Int!
  hasMore: Boolean!
  limit: Int!
  offset: Int!
}

type Person {
  id: String!
  firstname: String
  middlename: String
  lastname: String
  fullName: String
  normNameKey: String
  baseRowid: Int!
  primaryAddressId: Int
  name: String
  names(limit: Int = null, offset: Int = null): NameObservationConnection!
  addressAssociations(source: Source = null, role: AddressAssociationRole = null, limit: Int = null, offset: Int = null): PersonAddressAssociationConnection!
  propertyAssociations(source: Source = null, role: PropertyPersonRole = null, limit: Int = null, offset: Int = null): PropertyPersonAssociationConnection!
  organizationAssociations(source: Source = null, role: OrganizationPersonRole = null, limit: Int = null, offset: Int = null): PersonOrganizationAssociationConnection!
  contactAssociations(source: Source = null, limit: Int = null, offset: Int = null): PersonContactAssociationConnection!
  vehicleAssociations(source: Source = null, limit: Int = null, offset: Int = null): PersonVehicleAssociationConnection!
  sourceRecords(source: Source = null, limit: Int = null, offset: Int = null): SourceRecordConnection!
  addresses(relationTypes: [String!] = null, limit: Int = null, offset: Int = null): AddressConnection!
  contacts(limit: Int = null, offset: Int = null): ContactConnection!
  vehicles(limit: Int = null, offset: Int = null): VehicleConnection!
  edges(relationTypes: [String!] = null, limit: Int = null, offset: Int = null): EntityEdgeConnection!
  baseRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  taxRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  traceRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  autoRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  loanRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  driveRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  voterRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  criminalRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
  linkedinRecords(limit: Int = null, offset: Int = null): SourceRecordConnection!
}

type PersonAddressAssociation {
  id: Int!
  personId: String!
  addressId: Int!
  source: Source!
  role: AddressAssociationRole!
  sourceRowid: Int!
  confidence: Float
  observedDate: String
  person: Person
  address: Address
  provenance: [SourceRecord!]!
  sourceRecord: SourceRecord
}

type PersonAddressAssociationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PersonAddressAssociation!]!
}

type PersonConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [Person!]!
}

type PersonContactAssociation {
  id: Int!
  personId: String!
  contactId: Int!
  source: Source!
  role: String!
  sourceRowid: Int!
  confidence: Float
  person: Person
  contact: Contact
  provenance: [SourceRecord!]!
  sourceRecord: SourceRecord
}

type PersonContactAssociationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PersonContactAssociation!]!
}

type PersonOrganizationAssociation {
  id: Int!
  personId: String!
  organizationId: Int!
  source: Source!
  role: OrganizationPersonRole!
  sourceRowid: Int!
  observedDate: String
  person: Person
  organization: Organization
  provenance: [SourceRecord!]!
  sourceRecord: SourceRecord
}

type PersonOrganizationAssociationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PersonOrganizationAssociation!]!
}

type PersonSearchConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PersonSearchResult!]!
}

type PersonSearchResult {
  matchScore: Float!
  matchedFields: [String!]!
  person: Person
  nameObservation: NameObservation!
}

type PersonVehicleAssociation {
  id: Int!
  personId: String!
  vehicleId: Int!
  source: Source!
  role: String!
  sourceRowid: Int!
  confidence: Float
  person: Person
  vehicle: Vehicle
  provenance: [SourceRecord!]!
  sourceRecord: SourceRecord
}

type PersonVehicleAssociationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PersonVehicleAssociation!]!
}

input PersonWhereInput {
  id: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  fullName: StringFilterInput = null
  normNameKey: StringFilterInput = null
}

type Property {
  id: Int!
  propertyKey: String!
  source: Source!
  sourceRowid: Int!
  sourceRecords(source: Source = null, limit: Int = null, offset: Int = null): SourceRecordConnection!
  addresses(role: PropertyAddressRole = null, limit: Int = null, offset: Int = null): PropertyAddressAssociationConnection!
  people(role: PropertyPersonRole = null, limit: Int = null, offset: Int = null): PropertyPersonAssociationConnection!
  organizations(role: PropertyOrganizationRole = null, limit: Int = null, offset: Int = null): PropertyOrganizationAssociationConnection!
}

type PropertyAddressAssociation {
  id: Int!
  propertyId: Int!
  addressId: Int!
  source: Source!
  role: PropertyAddressRole!
  sourceRowid: Int!
  observedDate: String
  property: Property
  address: Address
  provenance: [SourceRecord!]!
  sourceRecord: SourceRecord
}

type PropertyAddressAssociationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PropertyAddressAssociation!]!
}

enum PropertyAddressRole {
  SITUS_ADDRESS
  MAILING_ADDRESS
}

type PropertyOrganizationAssociation {
  id: Int!
  propertyId: Int!
  organizationId: Int!
  source: Source!
  role: PropertyOrganizationRole!
  sourceRowid: Int!
  observedDate: String
  property: Property
  organization: Organization
  provenance: [SourceRecord!]!
  sourceRecord: SourceRecord
}

type PropertyOrganizationAssociationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PropertyOrganizationAssociation!]!
}

enum PropertyOrganizationRole {
  OWNER_ENTITY
  LENDER
  SERVICER
}

type PropertyPersonAssociation {
  id: Int!
  propertyId: Int!
  source: Source!
  role: PropertyPersonRole!
  sourceRowid: Int!
  personId: String
  displayName: String
  confidence: Float
  observedDate: String
  property: Property
  person: Person
  provenance: [SourceRecord!]!
  sourceRecord: SourceRecord
}

type PropertyPersonAssociationConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [PropertyPersonAssociation!]!
}

enum PropertyPersonRole {
  OWNER
  BUYER
  BORROWER
  TAXPAYER
  RECORDED_PARTY
}

type Query {
  baseRecord(id: String!): BaseRecord
  baseRecords(where: BaseRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): BaseRecordConnection!
  auto(id: String!): AutoRecord
  autos(where: AutoRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): AutoRecordConnection!
  criminal(id: String!): CriminalRecord
  criminals(where: CriminalRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): CriminalRecordConnection!
  drive(id: String!): DriveRecord
  drives(where: DriveRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): DriveRecordConnection!
  linkedin(id: String!): LinkedInRecord
  linkedins(where: LinkedInRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): LinkedInRecordConnection!
  loan(id: String!): LoanRecord
  loans(where: LoanRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): LoanRecordConnection!
  tax(id: String!): TaxRecord
  taxes(where: TaxRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): TaxRecordConnection!
  trace(id: String!): TraceRecord
  traces(where: TraceRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): TraceRecordConnection!
  utilities(where: UtilityRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): UtilityRecordConnection!
  voter(id: String!): VoterRecord
  voters(where: VoterRecordWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): VoterRecordConnection!
  person(id: String!): Person
  persons(where: PersonWhereInput = null, limit: Int = null, offset: Int = null): PersonConnection!
  address(id: Int!): Address
  resolveAddress(query: String!, zip: String = null): Address
  addressByText(query: String!, zip: String = null): Address
  addressByNormalized(normAddress: String!, zip: String!): Address
  property(id: Int!): Property
  organization(id: Int!): Organization
  vehicle(id: Int!): Vehicle
  contactPoint(id: Int!): Contact
  sourceRecord(source: Source!, rowid: Int!): SourceRecord
  addresses(where: AddressWhereInput = null, orderBy: [OrderByInput!] = null, limit: Int = null, offset: Int = null): AddressConnection!
  searchPersons(query: String!, limit: Int = null, offset: Int = null): PersonSearchConnection!
  searchPeople(query: String!, limit: Int = null, offset: Int = null): PersonSearchConnection!
  searchAddresses(query: String!, zip: String = null, limit: Int = null, offset: Int = null): AddressSearchConnection!
  peopleAtAddress(addressId: Int!, relationTypes: [String!] = null, limit: Int = null, offset: Int = null): PersonConnection!
  addressesForPerson(personId: String!, relationTypes: [String!] = null, limit: Int = null, offset: Int = null): AddressConnection!
}

enum Source {
  BASE
  TAX
  UTILITY
  TRACE
  AUTO
  LOAN
  DRIVE
  VOTER
  CRIMINAL
  LINKEDIN
}

type SourceRecord {
  source: Source!
  table: String!
  rowid: Int!
  recordId: String
  summary: String!
  data: JSON!
}

type SourceRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [SourceRecord!]!
}

input StringFilterInput {
  eq: String = null
  ne: String = null
  contains: String = null
  gt: String = null
  lt: String = null
  isNull: Boolean = null
  in: [String!] = null
}

type TaxRecord {
  rowid: Int!
  norm: TaxRecordNorm!
  id: String
  taxId: String
  address: String
  addressformal: String
  housenumber: String
  city: String
  state: String
  zip: String
  county: String
  firstname: String
  lastname: String
  ownername: String
  ownercompany: String
  owneraddressline1: String
  ownercity: String
  ownerstate: String
  ownerzipcode: String
  residential: String
  condo: String
  yearbuilt: String
  buildingarea: String
  totalmarketvalue: String
  totalassessedvalue: String
  taxvalue: String
  lendername: String
  buyeridcode: String
  recordingdate: String
  totalliencount: String
  totallienbalance: String
  equitycurrentestbal: String
  ltvcurrentestcombined: String
  totalfinancinghistcount: String
  foreclosecode: String
  forecloserecorddate: String
  ownerrescount: String
  person: Person
  propertyAddresses(limit: Int = null, offset: Int = null): AddressConnection!
  ownerMailingAddresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type TaxRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [TaxRecord!]!
}

type TaxRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
  owneraddressline1: String
}

input TaxRecordWhereInput {
  id: StringFilterInput = null
  taxId: StringFilterInput = null
  address: StringFilterInput = null
  addressformal: StringFilterInput = null
  housenumber: StringFilterInput = null
  city: StringFilterInput = null
  state: StringFilterInput = null
  zip: StringFilterInput = null
  county: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  ownername: StringFilterInput = null
  ownercompany: StringFilterInput = null
  owneraddressline1: StringFilterInput = null
  ownercity: StringFilterInput = null
  ownerstate: StringFilterInput = null
  ownerzipcode: StringFilterInput = null
  residential: StringFilterInput = null
  condo: StringFilterInput = null
  yearbuilt: StringFilterInput = null
  buildingarea: StringFilterInput = null
  totalmarketvalue: StringFilterInput = null
  totalassessedvalue: StringFilterInput = null
  taxvalue: StringFilterInput = null
  lendername: StringFilterInput = null
  buyeridcode: StringFilterInput = null
  recordingdate: StringFilterInput = null
  totalliencount: StringFilterInput = null
  totallienbalance: StringFilterInput = null
  equitycurrentestbal: StringFilterInput = null
  ltvcurrentestcombined: StringFilterInput = null
  totalfinancinghistcount: StringFilterInput = null
  foreclosecode: StringFilterInput = null
  forecloserecorddate: StringFilterInput = null
  ownerrescount: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type TraceRecord {
  rowid: Int!
  norm: TraceRecordNorm!
  id: String
  traceId: String
  phone: String
  cellphone: String
  email: String
  email02: String
  email03: String
  housenumber: String
  address: String
  city: String
  state: String
  zip: String
  county: String
  firstname: String
  middlename: String
  lastname: String
  dobDay: String
  dobMonth: String
  dobYear: String
  creditCapacity: String
  homeBuiltYear: String
  homePurchaseDate: String
  incomeDescription: String
  person: Person
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type TraceRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [TraceRecord!]!
}

type TraceRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
  phone: String
  cellphone: String
  email: String
  email02: String
  email03: String
}

input TraceRecordWhereInput {
  id: StringFilterInput = null
  traceId: StringFilterInput = null
  phone: StringFilterInput = null
  cellphone: StringFilterInput = null
  email: StringFilterInput = null
  email02: StringFilterInput = null
  email03: StringFilterInput = null
  housenumber: StringFilterInput = null
  address: StringFilterInput = null
  city: StringFilterInput = null
  state: StringFilterInput = null
  zip: StringFilterInput = null
  county: StringFilterInput = null
  firstname: StringFilterInput = null
  middlename: StringFilterInput = null
  lastname: StringFilterInput = null
  dobDay: StringFilterInput = null
  dobMonth: StringFilterInput = null
  dobYear: StringFilterInput = null
  creditCapacity: StringFilterInput = null
  homeBuiltYear: StringFilterInput = null
  homePurchaseDate: StringFilterInput = null
  incomeDescription: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type UtilityRecord {
  rowid: Int!
  norm: UtilityRecordNorm!
  firstName: String
  lastName: String
  middleName: String
  dob: String
  dod: String
  address: String
  city: String
  county: String
  state: String
  zip: String
  phone: String
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type UtilityRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [UtilityRecord!]!
}

type UtilityRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
  phone: String
}

input UtilityRecordWhereInput {
  firstName: StringFilterInput = null
  lastName: StringFilterInput = null
  middleName: StringFilterInput = null
  dob: StringFilterInput = null
  dod: StringFilterInput = null
  address: StringFilterInput = null
  city: StringFilterInput = null
  county: StringFilterInput = null
  state: StringFilterInput = null
  zip: StringFilterInput = null
  phone: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}

type Vehicle {
  id: Int!
  vin: String!
  personAssociations(source: Source = null, limit: Int = null, offset: Int = null): PersonVehicleAssociationConnection!
}

type VehicleConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [Vehicle!]!
}

type VoterRecord {
  rowid: Int!
  norm: VoterRecordNorm!
  id: String
  voterId: String
  phone: String
  mobile: String
  housenumber: String
  gender: String
  email: String
  zip: String
  address: String
  firstname: String
  lastname: String
  person: Person
  addresses(limit: Int = null, offset: Int = null): AddressConnection!
}

type VoterRecordConnection {
  pageInfo: PageInfo!
  totalCount: Int!
  hasMore: Boolean!
  nodes: [VoterRecord!]!
}

type VoterRecordNorm {
  firstname: String
  lastname: String
  nameKey: String
  address: String
  addressZipKey: String
  phone: String
  mobile: String
  email: String
}

input VoterRecordWhereInput {
  id: StringFilterInput = null
  voterId: StringFilterInput = null
  phone: StringFilterInput = null
  mobile: StringFilterInput = null
  housenumber: StringFilterInput = null
  gender: StringFilterInput = null
  email: StringFilterInput = null
  zip: StringFilterInput = null
  address: StringFilterInput = null
  firstname: StringFilterInput = null
  lastname: StringFilterInput = null
  nameKey: StringFilterInput = null
  addressZipKey: StringFilterInput = null
}
